### ISSUE TITLE
winless minify problem

### ISSUE THREAD

**Issue by stanca3101** [marklagendijk/WinLess#70] opened 2013-04-11 15:27 UTC
Hi. I have a problem with the winless 1.8. 
I have this code:
@mainColor: ~'<%= GetColor("MainColor") %>';
background: linear-gradient(@mainColor 0%, #e4e4e4 50%, @mainColor 100%);
and after compiling with winless i get the minfied version:
background:linear-gradient(<%= GetColor("MainColor") %>0%,#e4e4e4 50%,<%= GetColor("MainColor") %>100%);

when minifying the space after the ">" character is deleted and the property does not get set. Please help. I really need my css minified on a single line.

**Comment by jessewebb** [comment] 2013-05-28 21:37
We also use ASP tags in our LESS files. After upgrading from version 1.5 to version 1.8, we noticed that certain CSS styles were not working properly. It was very hard to diagnose the problem because the format of the minified files have change from multi-line (with line breaks) to a single line which makes the CSS files hard to diff. I assume this multi-line vs single-line change was made as part of [this issue](https://github.com/marklagendijk/WinLess/issues/47). Either way, we couldn't figure out what the difference was in the two different CSS files so we ended up rolling back to use version 1.5 of WinLess again. Maybe if this issue was solved, my problems would be resolved too. I really want to upgrade to the newest version of WinLess but we can't right now.

**Comment by marklagendijk** [comment] 2013-05-29 11:09
I've looked into this issue and it can't be really fixed by WinLess. Let me explain why.

LESS is made to generate CSS files. The LESS language has an official compiler. WinLESS uses the command line version of this compiler to actually compile (and minify the output of) the LESS files.

The problem which you guys are running into is caused by the fact that you are using LESS files to try to generate ASP files. Granted, these ASP files are mostly just CSS, but it's the ASP specific tags which are the problem.
LESS itself is flexible enough to let you use these tags (using string interpolation, as you showed in your example). But the CSS minifier (which is an external library which the official LESS compiler uses) is not. This makes sense: the purpose of a CSS minifier is to minify CSS files as good as possible. It shouldn't consider ASP tags.

So to conclude. You are perfectly able to use WinLESS to compile LESS files containing ASP tags, as long as you keep don't enable minification. If you really need minification (which you really don't, especially not if you make sure the requests get gzipped (which you should)), you should look for a way to minify the result of the response of the ASP file. However, if you make sure gzip is enabled, the gains of this are very small.

**Closed as completed by marklagendijk** 2013-05-29 11:09 UTC

**Comment by jessewebb** [comment] 2013-05-29 15:34
Thanks for the info @marklagendijk!

My team might have to reconsider how we will handle these ASP.NET tags in our LESS files but for now we are just sticking with the older version of WinLess (1.5.4) which seems to handle them without problems.

I haven't tried this yet but it might be possible to trick the minification step into handling ASP.NET tags properly. The work-around I am considering is using spaces surrounding the ASP.NET tags in the string literals.

```
@mainColor: ~' <%= GetColor("MainColor") %> ';
```

**Comment by marklagendijk** [comment] 2013-05-29 15:39
The older version of LESS.js has a own minifier. In later versions it has been replaced by an external library. WinLess 1.5.4 uses that older version of LESS.js.

I already tried that and it doesn't work. Makes sense: the minification is done after the compilation, so the extra space just gets removed.
