### ISSUE TITLE
Autocompile not working after restart

### ISSUE THREAD

**Issue by gaeld** [marklagendijk/WinLess#61] opened 2013-02-21 10:46 UTC
Hi, 

When i add a file for the first time in winless, the autocompile on save is working fine. At the restart of the computer, the autocompile on already added file don't work anymore. I've try to remove them from Winless, and re-add them, switching the options, nothing works. 
The only way is to rename the less file in something else.

I'm on Windows 8, 64bits.

**Comment by marklagendijk** [comment] 2013-03-02 16:21
If I understand you correctly the autocompile option doesn't work for already added files after a reboot? Do they compile correctly when you press the 'compile' button? Are the files located on your harddisk or on a network location?

**Comment by gaeld** [comment] 2013-03-05 09:18
That's exactly what happens. Already added files do not "auto-compile" after a reboot. They compile correctly with the button "Compile". 
The files are located on my harddisk, on a secondary partition (not the main one). 

edit : to make work after that, i need to remove the folder, remove the files, re-add the folder, re-add the files. And only then it works again.

**Comment by marklagendijk** [comment] 2013-05-29 11:40
Can you try the same with a file located on your primary partition, to see if that makes any difference?

**Comment by marklagendijk** [comment] 2013-07-13 17:47
Closed due to inactivity.

**Comment by matkokvesic** [comment] 2013-08-17 12:11
I have the same problem. Auto-compile simply doesn't trigger on Windows 8 (64bit). On Windows 7 (64bit) everything was fine. I tried running it as a administrator - no help.

**Comment by lmeyer** [comment] 2013-09-01 14:00
Same problem here (Windows 8 64bit). I tried running it as a administrator as well.

**Comment by gaeld** [comment] 2013-09-18 14:27
Hi, 
I've still have the same problem too. 
Putting the file on the Main Driver seems to be fixing the issue (sorry for the delay).

**Comment by woffleloffle** [comment] 2013-10-07 16:33
Confirming @gaeld's comment; I reproduced this bug.

Tracking a folder on any hard drive other than C:\ on Win8 will _not_ trigger the auto-compile when changing the *.less file.
Moving the same *.less files to the C:\ drive and then selecting the correlating *.css files on the other hard drive auto-compiles them correctly.

**Comment by marklagendijk** [comment] 2014-11-05 22:08
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.

**Closed as completed by marklagendijk** 2014-11-05 22:08 UTC
