### ISSUE TITLE
Latest twitter bootstrap error

### ISSUE THREAD

**Issue by gmhenderson** [marklagendijk/WinLess#1] opened 2012-02-27 01:37 UTC
I tried using WinLess with the latest twitter bootstrap and it simply won't compile bootstrap.less. No error is reported, and the compiler reports a successful compile, but no CSS file is actually created. I noticed folks using SimpLess are having a similar problem with the latest bootstrap. I'm not sure what's going on. (https://github.com/Paratron/SimpLESS/issues/33).

**@marklagendijk edit:**
To save everyone from reading this whole thread:
1)Twitter Bootstrap doesn't compile out of the box with the current version of WinLess + less.js (1.3.0).
2)The following fix/workaround solves this issue:
In mixin.less

``` css
// IE7 inline-block
// ----------------
.ie7-inline-block() {
  *display: inline;
  *zoom: 1;
  // comment to make it work with WinLESS
}
```

**Comment by guidupuy** [comment] 2012-03-09 23:36
Would love to see this fixed too. There seems to be a problem with the interpreter when using variables within a url() call. 

This can be fixed with the slightest change to the Bootstrap source though -  l. 24 & 31 of sprites.less, simply hardcode the path to the sprite files and voilà.

**Comment by fb16** [comment] 2012-03-22 04:23
Same problem here.

WinLess fails silently the compiling of the file "bootstrap.less" (which imports all the Bootstrap less files). 

So, the corresponding "bootstrap.css" file is not created. 

WinLess Compiler Staus logs success, though.

I have tried a solution, as the user guidupuy suggested, commenting the lines 24, 31 in "sprites.less" but with any success.

Are we the only ones to experience this problem with "bootstrap.less"?

Is this a problem related to WinLess?

Thank you

**Comment by marklagendijk** [comment] 2012-03-22 10:31
The problem with the latests version of bootstrap is caused by the following mixin in mixin.less:

``` css
// IE7 inline-block
// ----------------
.ie7-inline-block() {
  *display: inline; /* IE7 inline-block hack */
  *zoom: 1;
}
```

Atm, I have no idea why, but when you change it to something like this it works:

``` css
// IE7 inline-block
// ----------------
.ie7-inline-block() {
  *display: inline; /* IE7 inline-block hack */
  *zoom: 1;
  dummy: huh;
}
```

It will then compile correctly, but the 'dummy' declarations will appear in the output. Note: I tested this with less.js 1.3.0, WinLess will be updated to 1.3.0 shortly.

**Comment by fb16** [comment] 2012-03-22 11:27
Hi Mark,

thank you for taking the time to reply.

I read about your solution before, but that did not work.

It seems only a few are experiencing this problem. The following is my case.

Anyone could reproduce this? Thank you

---

## FOLDERS STRUCTURE

<pre>
root/
   ./bootstrap/less/bootstrap.less
   ./css/
   ./less/style.less
   ./index.html
</pre>


(within ./index.html)

<pre> 
link rel="stylesheet" href="css/style.css"
</pre>


(within ./less/style.less)

<pre> 
@import "../bootstrap/less/bootstrap.less"; 
</pre>


---

## STEPS

1) added the main root folder to WinLess GUI

2) and unchecked all less files but ./less/style.less
   so that WinLess now monitors only ./less/style.less

---

## EXPECTED RESULT

at saving of ./less/style.less
WinLess should generate the file css/style.css

---

## INSTEAD

at saving of ./less/style.less
WinLess does not generate the file css/style.css
but logs "success"

---

## TRIED SOLUTION

in ./bootstrap/less/mixin.less line 42 tried to change:

<pre>
// IE7 inline-block
// ----------------
.ie7-inline-block() {
  *display: inline; /* IE7 inline-block hack */
  *zoom: 1;
}
</pre>


into:

<pre>
// IE7 inline-block
// ----------------
.ie7-inline-block() {
  *display: inline; /* IE7 inline-block hack */
  *zoom: 1;
  dummy: huh;
}
</pre>


without success

**Comment by marklagendijk** [comment] 2012-03-22 12:00
Did you update your less.js manually to 1.3.0? I only tested with 1.3.0.

**Comment by fb16** [comment] 2012-03-22 12:35
Hello Mark,

Thank you. Have you been able to reproduce the problem?

Yes, I did update manually the less.js file to 1.3.0.

And I have tried substituting the less.js file with all the previous versions of less.js (minified).

Headache...

**Comment by marklagendijk** [comment] 2012-03-22 12:50
Didn't try it yet. Just released WinLess 1.4.0.

Gonna look into it now.

**Comment by marklagendijk** [comment] 2012-03-22 13:09
Tried it (using WinLess 1.4.0) and it compiles correctly (while using above mentioned fix).
Here is my testcase: http://files.web-mark.nl/winless/test/fb16_test.zip

**Comment by fb16** [comment] 2012-03-22 13:46
Thank you for sending the test case, and for updating WinLess to 1.4.0. 

I will attempt later and I will inform you.

Thank you very much

**Comment by fb16** [comment] 2012-03-22 15:12
Hi Mark,

I am sorry for the extra work I caused.

Actually, it turned out that the culprit were the following lines I added in "./bootstrap/less/variables.less".

I suppose it is something related with the floating-point numbers. Here they are:

<pre>
// Fluid grid
// -------------------------
// @fluidGridColumnWidth:    6.382978723%;
// @fluidGridGutterWidth:    2.127659574%;

@fluidGridColumnWidth:    7.368421052631579%
@fluidGridGutterWidth:    1.052631578947368%
</pre>


As an aside, I am pleased with the new feature to check/uncheck all files in the list.

Thank you. For any question feel free to ask.

Regards

**Comment by marklagendijk** [comment] 2012-03-22 15:18
No problem. Glad you got it sorted out.

The check all is really handy when you have something like bootstrap in your list. Saves you 20+ clicks :).

**Comment by fb16** [comment] 2012-03-22 15:59
;-)  agree!

just let me congratulate with myself now, for having missed the final semi-colons in the "variables.less" lines.

I could start crying, but I won't.

Regards

**Comment by marklagendijk** [comment] 2012-03-22 17:09
Lol, the life of a programmer is very hard. How much time did you waste on this?

I once spend a whole day to solve a bug which was caused by a casing error:

``` c#
private string myProperty;
public string MyProperty {
    get {
        // should have been 'myProperty', this causes an endless loop
        return MyProperty;
    }
}

```

The endless loop crashed the webserver but I had no idea what was causing it.

**Comment by fb16** [comment] 2012-03-22 18:19
That was risky -DDD

Luckily for you "c#" never met me! :-)

Regards

**Comment by tcrosen** [comment] 2012-03-23 18:20
I still can't compile the Twitter Bootstrap with the newest version (1.4.0).

## Screenshots below:
1. No CSS
2. Compile with Node.js and lessc.cmd
3. CSS successfully created
   ![](http://i43.tinypic.com/4vhhk8.png)

---
1. No CSS
2. Compile with lessc.wsf
3. No output, no CSS
   ![](http://i43.tinypic.com/301k55h.png)

---
1. Compile with WinLess
2. Error(s)
   ![](http://i39.tinypic.com/34ytbn4.png)

Full size:
http://i39.tinypic.com/34ytbn4.png

**Comment by marklagendijk** [comment] 2012-03-27 07:56
To compile bootstrap with WinLess (or less.wsf, which is actually the same thing because WinLess uses less.wsf) you still need to apply above mentioned fix to make it work.

What I didn't know is that it does work when you compile via Node.js

**Comment by KrunchMuffin** [comment] 2012-04-08 18:00
I am getting the error  "'eval' is null or not an object". just downloaded WinLESS and bootstrap both.

**Comment by jjkester** [comment] 2012-04-09 20:36
Today I got the same result with the latest version: I tried the fix mentioned above, but still no output file (although WinLESS didn't report any errors - it just reported that compiling was succesful). Any idea's?

**Comment by LimeBlast** [comment] 2012-04-10 11:27
I'm also having an issue with the latest build of WinLess (1.5.3) trying to compile boilerplate. I've tried the solutions for the mixins.less file listed above, but it still doesn't work - instead I get a success message, but the compiled file doesn't appear.

**Comment by scromar** [comment] 2012-04-11 14:04
I'm also experiencing this, and the fix does not work for me either. At this point none of the Windows focused tools (SimpLESS, Crunch, WinLESS) can compile the Bootstrap less files. I like WinLESS, so I hope that the error that is resulting in no output can be tracked down. Thanks for all of your work on this project.

**Comment by LimeBlast** [comment] 2012-04-11 14:07
A minor update on my issue - I didn't realise that it was different, but I was trying to compile the less files that come with http://www.rootstheme.com/ - and as a result, was having the issues listed above.

I've managed to fix this, however, by replacing the less files in the roots theme with the latest from the bootstrap download and (after doing the .ie7-inline-block() fix listed in the first post) it was compiling again.

**Comment by scromar** [comment] 2012-04-11 14:55
I grabbed a clean version of the latest bootstrap less files, and I can confirm what LimeBlast says: it does indeed compile with the .ie7-inline-block() fix. I had some modified files that were not compiling, but it must be for some other reason.

**Comment by jjkester** [comment] 2012-04-11 17:46
Although I still find it stange (when I first commented here I just modified some colors in the Bootstrap LESS files) I can confirm what both LimeBlast and scromar mentioned above.

**Comment by LimeBlast** [comment] 2012-04-11 17:48
There is still, obviously, a problem somewhere, as before I changed the less files, it was reporting a successful compile, when in fact it wasn't.

**Comment by jeffwhitfield** [comment] 2012-05-25 14:18
One other option for the .ie-7-inline-block bug would be to simply dupe the display property:

// IE7 inline-block
// ----------------
.ie7-inline-block() {
  display: inline;
  _display: inline; /_ IE7 inline-block hack */
  *zoom: 1;
}

Doesn't effect the desired outcome and you don't end up with a bogus dummy property.  I think what's tripping it up is having no valid properties in the statement. Being that the error doesn't happen when you compile natively with LESS 1.3 I would assume the issue is how WinLESS loops through the properties. Hopefully this little finding should help in programming a solution to this bug.  :)

**Comment by replete** [comment] 2012-07-24 11:36
Just to +1, the fix suggest at the top resolved the issue for me.

**Comment by marklagendijk** [comment] 2012-11-27 00:43
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).

**Closed as completed by marklagendijk** 2012-11-27 00:43 UTC
