### ISSUE TITLE
Is there any way to select multiple files so that you can select an output folder just once?

### ISSUE THREAD

**Issue by basher** [marklagendijk/WinLess#19] opened 2012-05-17 08:03 UTC
Hi Mark,

This is the scenario we have implemented at work:

We have small, modular CSS files, located in many "module-specific" folders.
Our CMS template system with all possible modules amounts to nearly 100 CSS files.

We have placed all the LESS files into a separate folder (so that we can keep LESS and CSS files separate), but with the same modular sub-folder structure to mimic production CSS structure.

When we roll out a new site, we will have to copy all LESS files to new project folder.
Then we will have to select the output folder for each file individually.

It would be nice if we could select multiple files for this operation.

Any plans for something like this??

Cheers,
Kev.

**Comment by jfrux** [comment] 2012-05-18 12:38
DUPLICATE OF #9

**Closed as completed** 2012-05-18 21:31 UTC
