### ISSUE TITLE
Error when compiling twitterbootstrap buttons.less on WinLess

### ISSUE THREAD

**Issue by maxisam** [marklagendijk/WinLess#25] opened 2012-07-01 21:21 UTC
This is the problem and walk around. I guess something wrong with /\* */ and mixins

http://stackoverflow.com/questions/11285295/error-when-compiling-twitterbootstrap-buttons-less-on-winless/11285675#11285675

**Comment by foiseworth** [comment] 2012-07-07 16:10
I think this is a duplicate of issue #1 and should therefore be closed?

**Closed as completed** 2012-07-07 17:28 UTC
