### ISSUE TITLE
Atuocompile @import files doesn't wrok

### ISSUE THREAD

**Issue by rahmansal** [marklagendijk/WinLess#45] opened 2012-11-10 11:31 UTC
As in twitter bootstrap i have a main.less file where i import all other files like form.less, buttons.less ... etc but when i made changes to any of these imported files i have to hit the compile button **manually** for winless to compile it! Unlike simpless it compiles it perfectly!

**Comment by marklagendijk** [comment] 2012-11-27 00:51
Duplicate of #18

**Closed as completed by marklagendijk** 2012-11-27 00:51 UTC
