### ISSUE TITLE
Could not load file or assembly 'PresentationFramework

### ISSUE THREAD

**Issue by ghost** [marklagendijk/WinLess#67] opened 2013-04-06 03:15 UTC
I get the following error when I click on "Add Folder". Note: I am able to drop a folder into the "Less Files" dialog box as a workaround, so I am able to function. Please let me know if you need any additional info, if you know how to fix this, if you have fixed it or if I need to do something on my end. I hope this is helpful.
Regards, Peter

![image](https://f.cloud.github.com/assets/4074596/346848/1d613494-9e68-11e2-8784-00dda8aaed13.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Ookii.Dialogs.Wpf.VistaFolderBrowserDialog.ShowDialog()
   at WinLess.mainForm.addDirectoryButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5466 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

WinLess
    Assembly Version: 1.8.0.0
    Win32 Version: 1.8.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Mark%20Lagendijk/WinLess/WinLess.exe

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5468 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

NDesk.Options
    Assembly Version: 0.2.1.0
    Win32 Version: 0.2.1.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Mark%20Lagendijk/WinLess/NDesk.Options.DLL

System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

Ookii.Dialogs.Wpf
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Mark%20Lagendijk/WinLess/Ookii.Dialogs.Wpf.DLL

System.Deployment
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Deployment/2.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll

t94kq25g
    Assembly Version: 1.8.0.0
    Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by marklagendijk** [comment] 2013-04-06 11:42
It looks like this issue is caused by the .NET Framework which WinLess requires. When you click on 'Add folder' a feature which requires at least .NET 3.0 is being used, which you apparently don't have installed.

I think you issue can be fixed by installing the latest [.NET Framework (4.5)](http://www.microsoft.com/en-us/download/details.aspx?id=30653). Let me know if this fixes your issue.

Normally the installer should check any requirements, and download them when they are not available, but this option is not available in the setup builder which I am currently using.

**Comment by ghost** [comment] 2013-04-06 15:13
Mark, THANK YOU for your reply.

That is not correct. I am running .NET 4.0.30319 (64bit) Windows 7 Professional SP1. Please see the attached screenshots of the directory listing of my Windows\Microsoft.Net directory and basic Windows Info. I’m not sure if this is absolute proof of my .NET version, but it might be. Also, FYI, I am doing software development using Visual Studio 2010.

In case you are interested, I have a facility that allows you to share my desktop, in case you want to see firsthand this failing and maybe look around for the cause. If this is desired, just send me your contact info including phone number and a proposed date/time.

Also, I am NOT saying there are no problems with my system. Anything is possible. I just believe the .Net version is not the problem,

Regards,

Peter

---

Peter Schmidt 
PRS Technologies, Inc. 

Brookeville, MD 20833-2520

office:    301-570-6795 x111

mobile:  301-404-4403

email:    peter@prstech.com 
web:     www.prstech.com http://www.prstech.com/

**Comment by marklagendijk** [comment] 2013-04-06 17:44
Can you verify that the file `PresentationFramework.dll` does exist under `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF`?
Because you are the first to report this error, it seems logical that the problem is specific to your installation. Could you try to run this[.NET Framework Repair tool](http://www.microsoft.com/en-us/download/details.aspx?id=30135)?

**Comment by ghost** [comment] 2013-04-06 19:12
Mark, I did have WPF PresentationFramework.dll installed. See screenshow below.

I ran the repair tool. It did find some issues, but they didn’t fix the problem.

See the FOUR screenshots below of the Properties of the PresentationFramework.dll file.

See the other screenshots below to see how the repair went and finally your tool failing again.

I hope this helps. I am available today if you want to come to my desktop and check it out.

Regards,

Peter

---

---

Peter

---

Peter Schmidt 
PRS Technologies, Inc. 

20517 Riggs Hill Way

Brookeville, MD 20833-2520

office:    301-570-6795 x111

mobile:  301-404-4403

email:    peter@prstech.com 
web:     www.prstech.com http://www.prstech.com/

**Comment by marklagendijk** [comment] 2013-04-06 20:16
Hey Peter,
Because you are emailing via GitHub, I'm not getting your attachments. Please email them to info@winless.org.
I don't have time today to check it out via remote desktop. Also I don't think that I would find anything.

The only thing I can think of, which you could try is to download the WinLess source, open the Visual Studio solution and press F5 (build + open in debugmode). That might lead to some extra information on what the problem is.

Cheers,

Mark

**Comment by ghost** [comment] 2013-04-06 20:21
Sorry, I didn’t know.

I resent to info@winless.org.

Just checking – the “WinLess source” is what you wrote ??

Peter

---

Peter Schmidt 
PRS Technologies, Inc. 

20517 Riggs Hill Way

Brookeville, MD 20833-2520

office:    301-570-6795 x111

mobile:  301-404-4403

email:    peter@prstech.com 
web:     www.prstech.com http://www.prstech.com/

**Comment by greggberry** [comment] 2013-04-18 10:48
I have the same issue even with .net 4.5 installed. The repair tool did nothing either.

**Comment by neilscott** [comment] 2013-05-14 07:18
I have the same issue.

**Comment by greggberry** [comment] 2013-05-14 07:54
Not sure if this helps anyone but make sure that the .NET framework 3.5.1 checkbox is on in windows control panel > turn windows features on or off. That seemed to have resolved my isssue.

**Comment by marklagendijk** [comment] 2013-05-29 11:33
@Pschmidt2, @neilscott : can you verify whether your problem can be solved by @greggberry 's solution?

**Comment by maxx0r** [comment] 2013-09-30 08:38
Did the trick for me (for future reference). Dont forget to restart winless tho

**Comment by marklagendijk** [comment] 2014-11-05 22:09
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.

**Closed as completed by marklagendijk** 2014-11-05 22:09 UTC
