### ISSUE TITLE
Winless 1.8.1 don't update less 1.4.1 to 1.4.2

### ISSUE THREAD

**Issue by rhermann** [marklagendijk/WinLess#84] opened 2013-07-22 13:32 UTC
Related to https://github.com/marklagendijk/WinLess/issues/80 Winless 1.8.1 do not update 1.4.1 less version to 1.4.2

"Successfully updated ... to 1.4.1"

**Comment by marklagendijk** [comment] 2013-07-29 13:31
Duplicate of #82.

**Closed as completed by marklagendijk** 2013-07-29 13:31 UTC
